
type SemVerString = `${number}.${number}.${number}`;
export interface ModuleRelease {
    releaseVersion: SemVerString,
    modVersion: SemVerString,
    changelog: string,
    modulePath: string,
}

// Generated by https://quicktype.io

export interface Account {
    id:    number;
    name:  string;
    rank:  string;
    email: string;
    cookies: string
}

